name: scanner

description: "A poject for Homs's finance"

publish_to: 'none' # Remove this line if you wish to publish to pub.dev


version: 1.0.0+1

environment:
  sdk: ^3.9.2

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  gap: ^3.0.1
  animated_floating_buttons: ^0.0.2
  bot_toast: ^4.1.3
  icons_launcher: ^3.0.3
  flutter_svg: ^2.0.14
  carousel_slider: ^5.0.0
  responsive_framework: ^1.5.1 
  shared_preferences: ^2.3.3
  json_theme: ^11.0.0
  i18n_extension: ^15.0.0
  i18n_extension_importer: ^0.0.6
  go_router: ^17.0.1 
  provider: ^6.1.2
  flutter_riverpod: ^3.0.3
  http: ^1.2.2
  reactive_forms: ^18.1.1
  reactive_phone_form_field: ^5.0.0
  reactive_flutter_rating_bar: ^2.0.1
  reactive_dropdown_search: ^6.0.0-pre4
  reactive_pinput: ^5.0.0
  flutter_quill: ^11.0.0
  animated_splash_screen: ^1.3.0
  firebase_core: ^4.2.0 # Core for Firebase
  cloud_firestore: ^6.0.3 # For Could Firestore Database
  # firebase_auth: ^6.1.1
  # google_sign_in: ^7.2.0
  google_sign_in: ^7.2.0
  firebase_auth: ^6.1.1
  json_annotation: ^4.9.0
  riverpod_annotation: ^4.0.0
  freezed_annotation: ^3.0.0
  font_awesome_flutter: ^10.8.0
  country_flags: ^4.1.0
  image_picker: ^1.1.2
  firebase_storage: ^13.0.3
  share_plus: ^12.0.1
  firebase_messaging: ^16.0.3
  phone_numbers_parser: ^9.0.0
  url_launcher: ^6.3.0
  # flutter_local_notifications: ^19.5.0 #اشعارات
  timezone: ^0.10.1 
  flutter_timezone: ^5.0.1 #تحديد الموقع
  permission_handler: ^12.0.1 #صلاحيات الاشعارات
  android_alarm_manager_plus: ^5.0.0 #تجديد الاشعارات في الخلفية
  workmanager: ^0.9.0+3
  firebase_app_check: ^0.4.1+4
  supabase_flutter: ^2.0.0
  flutter_secure_storage: ^9.0.0
  dio: ^5.9.1
  pdf: ^3.10.8
  printing: ^5.11.0
  path_provider: ^2.1.1
  cunning_document_scanner: ^1.1.0
  syncfusion_flutter_pdfviewer: ^28.1.33


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  freezed: ^3.0.2
  build_runner: ^2.4.14
  json_serializable: ^6.9.3
  riverpod_generator: ^4.0.0+1
# flutter_lints: ^5.0.0


flutter:

  uses-material-design: true

  assets:
    - assets/themes/
    - assets/translations/
    - assets/images/
    - assets/svg/

  fonts:
    - family: Rubik
      fonts:
        - asset: assets/fonts/Rubik-Regular.ttf

icons_launcher:
  image_path: "assets/images/icon.png"
  platforms:
    android:
      enable: true
    web:
      enable: true